name: core
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ">=3.3.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  logger: ^1.4.0
  intl: ^0.18.1
  dropdown_search: ^5.0.6
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.2
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  animated_toggle_switch: ^0.8.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  go_router: ^14.2.7
  validatorless: ^1.2.3
  dart_ping: ^9.0.1
  smooth_scroll_multiplatform: ^1.0.8
  vph_web_date_picker: ^0.0.6
  dart_pusher_channels: ^1.2.2+1
  permission_handler: ^11.3.1
  device_info_plus: ^10.1.2
  dropdown_button2: ^2.3.9
  package_info_plus: ^8.0.2
  responsive_builder: ^0.7.0
  flutter_switch: ^0.3.2
  pull_to_refresh_new: ^2.0.5
  ota_update: ^6.0.0
  fleather: ^1.14.5+1
  url_launcher: ^6.3.1
  flutter_pdfview: ^1.3.2
  image_picker: ^1.1.2
  flutter_image_compress: ^2.3.0
  calendar_date_picker2: ^1.1.8

publish_to: none

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.6
  freezed: ^2.1.1
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
